sudo: required
services:
  - docker

before_install:
  - docker build -t multi-container -f ./client/Dockerfile.dev ./client

script:
  - docker run multi-container npm test -- --coverage

after_success:

  - docker build -t multi-container/client ./client
  - docker build -t multi-container/server ./server
  - docker build -t multi-container/nginx ./nginx
  - docker build -t multi-container/worker ./worker
  # Log into Docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the builded images into Docker hub

  - docker push multi-container/client
  - docker push multi-container/server
  - docker push multi-container/nginx
  - docker push multi-container/worker